### ISSUE TITLE
Installing tinker-engine from built wheel causes import errors

### ISSUE THREAD

**Issue by Purg** [tinker-engine/tinker-engine#137]
Currently assuming 2 things:
* tinker-engine should be pip-installable in the future, which requires either a source distribution or a wheel
* wheels or source dists are created via `python setup.py bdist_wheel` or `python setup.py sdist`, respectively

If I installed tinker-engine from a built dist, the runtime requirements I observe in the `Pipfile`'s "packages" section, are not being honored. This would be because the `setup.py` file's `install_requires` metadata is being populated with the contents of the `requirements.txt` file which is empty. This will of course lead to import errors.

```bash
(tinker) paul.tunison@rivellon tinker-engine (master) $ clear
(tinker) paul.tunison@rivellon tinker-engine (master) $ pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 53.0.0
wheel      0.36.2
(tinker) paul.tunison@rivellon tinker-engine (master) $ python setup.py bdist_wheel
...
(tinker) paul.tunison@rivellon tinker-engine (master) $ pip install dist/tinker_engine-0.8.0-py3-none-any.whl 
Processing ./dist/tinker_engine-0.8.0-py3-none-any.whl
Installing collected packages: tinker-engine
Successfully installed tinker-engine-0.8.0
(tinker) paul.tunison@rivellon tinker-engine (master) $ python
Python 3.6.8 (default, Aug 24 2020, 17:57:11) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinker.algorithm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/KHQ/paul.tunison/dev/tinker-engine/tinker/algorithm.py", line 4, in <module>
    from smqtk_core import Configurable, Pluggable
ModuleNotFoundError: No module named 'smqtk_core'
>>> import tinker.configuration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/KHQ/paul.tunison/dev/tinker-engine/tinker/configuration.py", line 5, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by waxlamp** [comment]
Thanks for filing this detailed issue, @Purg. Figuring out correct building and release is something we obviously haven't done yet, and this will be a good start.

This issue is also related to #118, and if possible I'd love to use the newer TOML file based setup systems.

**Comment by Purg** [comment]
:+1: I have a TODO myself to move to pypackage method of things for the SMQTK world (at least after this first round of publishing breakout packages). Which ever way is used to specify install requirements appropriately such that they are represented in built distribution packages would resolve this issue.

**Comment by Purg** [comment]
Maybe we can discuiss soonish a standard poetry based process to maybe apply to both SMQTK and here.

**Comment by Purg** [comment]
Upon some further thought, the Pipenv contextualized issue is that `typing_extensions` is not listed in the `[packages]` section since as things are the package has a parimary requirement on that package being installed.
