### ISSUE TITLE
Smqtk example is not working based on the instructions

### ISSUE THREAD

**Issue by as6520** [tinker-engine/tinker-engine#147]
I trying to run the smqtk example and I am running into the following error
```
Traceback (most recent call last):
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/bin/tinker", line 8, in <module>
    sys.exit(main())
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/lib/python3.7/site-packages/tinker/main.py", line 122, in main
    protocols = protocol.Protocol.get_impls()
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/lib/python3.7/site-packages/smqtk_core/plugin.py", line 378, in get_impls
    *discover_via_env_var(cls.PLUGIN_ENV_VAR),
  File "/home/ameya/.cache/pypoetry/virtualenvs/sail-on-client-GduJW6xq-py3.7/lib/python3.7/site-packages/smqtk_core/plugin.py", line 190, in discover_via_env_var
    m = importlib.import_module(path)
  File "/home/ameya/.pyenv/versions/3.7.10/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'examples'
```

**Comment by as6520** [comment]
Closing since it worked after
```
pipenv install --dev
```
