### ISSUE TITLE
Dev/parinterfaceupdates - [merged]

### ISSUE THREAD

**Issue by waxlamp** [tinker-engine/tinker-engine#76]
In GitLab by @Schumann on Jun 1, 2020, 13:27

_Merges dev/parinterfaceupdates -> development_

changes to the parinterface file required because of changes to the par server.

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 13:28

@waxlamp I made some changes over the weekend due to changes to the par server, as well as debugging. Please review. Once these changes are approved, I can move all of the interface files out of the framework.

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 13:28

@cfunk1210 I made some changes over the weekend due to changes to the par server, as well as debugging. Please review. Once these changes are approved, I can move all of the interface files out of the framework.

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 13:37

added 21 commits

<ul><li>3c57200b...5b597672 - 20 commits from branch <code>development</code></li><li>7e61d687 - Merge branch &#39;development&#39; into dev/parinterfaceupdates</li></ul>

[Compare with previous version](/darpa_learn/framework/-/merge_requests/21/diffs?diff_id=113307&start_sha=3c57200bf2ac58f50d85f4bd2ad5459aaa98eca5)

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:21

added 1 commit

<ul><li>9f75e0de - fix broken merge</li></ul>

[Compare with previous version](/darpa_learn/framework/-/merge_requests/21/diffs?diff_id=113316&start_sha=7e61d687e2706267aa729c89fde7ecb664bb1349)

**Comment by waxlamp** [comment]
In GitLab by @waxlamp on Jun 1, 2020, 14:23

Commented on [framework/main.py line 41](https://github.com/tinker-engine/tinker-engine/compare/19b286282a530764cf41f8af733276b05962637c..0151cbd7b8d70b26bdcafc53538875a96e8beb10#diff-ebafe5c711cb830fec9b7de8fb5eb129R41)



If these packages are moving out of the framework repository, it seems that these import statements won't work anymore?

**Comment by waxlamp** [comment]
In GitLab by @waxlamp on Jun 1, 2020, 14:23

Commented on [framework/main.py line 120](https://github.com/tinker-engine/tinker-engine/compare/5b5976725bfafdbefe0a12d22b291e2258b82298..9f75e0de86e1c5ac6d4a9562765211da3dcd277b#diff-ebafe5c711cb830fec9b7de8fb5eb129R120)



Is this debugging output?

**Comment by waxlamp** [comment]
In GitLab by @waxlamp on Jun 1, 2020, 14:23

Commented on [framework/main.py line 123](https://github.com/tinker-engine/tinker-engine/compare/5b5976725bfafdbefe0a12d22b291e2258b82298..9f75e0de86e1c5ac6d4a9562765211da3dcd277b#diff-ebafe5c711cb830fec9b7de8fb5eb129R123)



Is this debugging output?

**Comment by waxlamp** [comment]
In GitLab by @waxlamp on Jun 1, 2020, 14:23

Commented on [framework/main.py line 218](https://github.com/tinker-engine/tinker-engine/compare/5b5976725bfafdbefe0a12d22b291e2258b82298..9f75e0de86e1c5ac6d4a9562765211da3dcd277b#diff-ebafe5c711cb830fec9b7de8fb5eb129R218)



Is this debugging output?

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:23

Commented on [framework/main.py line 41](https://github.com/tinker-engine/tinker-engine/compare/19b286282a530764cf41f8af733276b05962637c..0151cbd7b8d70b26bdcafc53538875a96e8beb10#diff-ebafe5c711cb830fec9b7de8fb5eb129R41)



That's not this MR, that is the next one after this.

**Comment by waxlamp** [comment]
In GitLab by @waxlamp on Jun 1, 2020, 14:24

The substantive changes look ok--they look similar to changes I saw happening in the original sail-on repo.

I left a few comments about nitpicky stuff, but on the whole this LGTM.

**Comment by waxlamp** [comment]
In GitLab by @waxlamp on Jun 1, 2020, 14:24

Commented on [framework/main.py line 41](https://github.com/tinker-engine/tinker-engine/compare/19b286282a530764cf41f8af733276b05962637c..0151cbd7b8d70b26bdcafc53538875a96e8beb10#diff-ebafe5c711cb830fec9b7de8fb5eb129R41)



Gotcha.

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:24

Commented on [framework/main.py line 120](https://github.com/tinker-engine/tinker-engine/compare/5b5976725bfafdbefe0a12d22b291e2258b82298..9f75e0de86e1c5ac6d4a9562765211da3dcd277b#diff-ebafe5c711cb830fec9b7de8fb5eb129R120)



changed this line in [version 5 of the diff](/darpa_learn/framework/-/merge_requests/21/diffs?diff_id=113317&start_sha=9f75e0de86e1c5ac6d4a9562765211da3dcd277b#9a336ce386b6d7996bffd61f35bcbed014898ce6_120_120)

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:24

Commented on [framework/main.py line 123](https://github.com/tinker-engine/tinker-engine/compare/5b5976725bfafdbefe0a12d22b291e2258b82298..9f75e0de86e1c5ac6d4a9562765211da3dcd277b#diff-ebafe5c711cb830fec9b7de8fb5eb129R123)



changed this line in [version 5 of the diff](/darpa_learn/framework/-/merge_requests/21/diffs?diff_id=113317&start_sha=9f75e0de86e1c5ac6d4a9562765211da3dcd277b#9a336ce386b6d7996bffd61f35bcbed014898ce6_123_122)

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:24

Commented on [framework/main.py line 218](https://github.com/tinker-engine/tinker-engine/compare/5b5976725bfafdbefe0a12d22b291e2258b82298..9f75e0de86e1c5ac6d4a9562765211da3dcd277b#diff-ebafe5c711cb830fec9b7de8fb5eb129R218)



changed this line in [version 5 of the diff](/darpa_learn/framework/-/merge_requests/21/diffs?diff_id=113317&start_sha=9f75e0de86e1c5ac6d4a9562765211da3dcd277b#9a336ce386b6d7996bffd61f35bcbed014898ce6_218_216)

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:24

added 1 commit

<ul><li>e39caf48 - remove debugging statements</li></ul>

[Compare with previous version](/darpa_learn/framework/-/merge_requests/21/diffs?diff_id=113317&start_sha=9f75e0de86e1c5ac6d4a9562765211da3dcd277b)

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:25

Commented on [framework/main.py line 120](https://github.com/tinker-engine/tinker-engine/compare/5b5976725bfafdbefe0a12d22b291e2258b82298..9f75e0de86e1c5ac6d4a9562765211da3dcd277b#diff-ebafe5c711cb830fec9b7de8fb5eb129R120)



Just pushed with them removed

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 1, 2020, 14:25

@cfunk1210 Can you test this with Learn. I verified it with sail-on.

**Comment by waxlamp** [comment]
In GitLab by @waxlamp on Jun 1, 2020, 14:57

resolved all threads

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 2, 2020, 10:42

added 4 commits

<ul><li>e39caf48...19b28628 - 3 commits from branch <code>development</code></li><li>0151cbd7 - Merge branch &#39;development&#39; into dev/parinterfaceupdates</li></ul>

[Compare with previous version](/darpa_learn/framework/-/merge_requests/21/diffs?diff_id=113441&start_sha=e39caf4812308ab3d5a4567a2de0188e1b81d7ba)

**Comment by waxlamp** [comment]
In GitLab by @cfunk1210 on Jun 2, 2020, 11:53

I keep getting this error which I thought was fixed in Eric's last branch.  
```
(learn) chris@funk:~/code/DARPA_LEARN/learn$ framework -a learn/algorithms -i JPLInterface  learn/protocol/learn_protocol.py
Using this URL: https://api-staging.lollllz.com/
Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/learn/bin/framework", line 11, in <module>
    load_entry_point('framework', 'console_scripts', 'framework')()
  File "/home/chris/code/DARPA_LEARN/framework/framework/main.py", line 226, in main
    execute()
  File "/home/chris/code/DARPA_LEARN/framework/framework/main.py", line 175, in execute
    protocol = obj(discovered_plugins, algorithmsbasepath, harness)
TypeError: __init__() takes 3 positional arguments but 4 were given
(learn) chris@funk:~/code/DARPA_LEARN/learn$ cd ..
(learn) chris@funk:~/code/DARPA_LEARN$ framework -a learn/learn/algorithms -i JPLInterface  learn/learn/protocol/learn_protocol.py
Using this URL: https://api-staging.lollllz.com/
Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/learn/bin/framework", line 11, in <module>
    load_entry_point('framework', 'console_scripts', 'framework')()
  File "/home/chris/code/DARPA_LEARN/framework/framework/main.py", line 226, in main
    execute()
  File "/home/chris/code/DARPA_LEARN/framework/framework/main.py", line 175, in execute
    protocol = obj(discovered_plugins, algorithmsbasepath, harness)
TypeError: __init__() takes 3 positional arguments but 4 were given
```

**Comment by waxlamp** [comment]
In GitLab by @cfunk1210 on Jun 2, 2020, 11:54

I'm on this branch of the framework.  `0151cbd7 Eric Schumann <eric.schumann@kitware.com> on 6/2/20 at 10:42 AM`

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 2, 2020, 12:03

You are on an outdated branch of the learn repo. Your learn_protocol.py file has the old version of the `Learn` class which has only 3 of the 4 init args.

**Comment by waxlamp** [comment]
In GitLab by @cfunk1210 on Jun 2, 2020, 12:10

let me try a better branch

**Comment by waxlamp** [comment]
In GitLab by @cfunk1210 on Jun 2, 2020, 12:13

New branch worked fine.  Need to rebase my pretrained branch I guess. Testing image classification and object detection now.

**Comment by waxlamp** [comment]
In GitLab by @cfunk1210 on Jun 2, 2020, 12:14

Seems to have worked for random baselines.

**Comment by waxlamp** [comment]
In GitLab by @cfunk1210 on Jun 2, 2020, 12:14

resolved all threads

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 2, 2020, 12:23

merged

**Comment by waxlamp** [comment]
In GitLab by @Schumann on Jun 2, 2020, 12:23

mentioned in commit 11ba0c0a72ceb4defcf47fd1f6a80905ae294e49
